lane :unit do
    test(project: ENV['project'], scheme: ENV['scheme'], device: ENV['device'])
    report(project: ENV['project'], scheme: ENV['scheme'])
end

private_lane :test do |params|
    scan(project: params[:project],
        devices: params[:device],
        scheme: params[:scheme],
        code_coverage: true
    )
end

private_lane :report do |params|
    xcov(
        project: params[:project],
        scheme: params[:scheme],
        output_directory: "./Report",
        only_project_targets: true
    )
end