name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      run: make unit platform=ios
    # - name: Run tests
    #   run: swift test -v
